config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('prod.urls', namespace='prod')),
    path('users/', include('users.urls', namespace='users')),
]

prod/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from prod.apps import ProdConfig
from prod.views import *

app_name = ProdConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='product'),
    path('product_create/', ProductCreateView.as_view(), name='product_create'),
    path('product_update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('product_delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
    path('product_detail/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='product_detail'),
    path('category_create/', CategoryCreateView.as_view(), name='category_create'),
    path('category_list/', CategoryListView.as_view(), name='category_list')
]

users/urls.py
from django.contrib.auth.views import LogoutView, PasswordResetView
from django.urls import path
from users.apps import UsersConfig
from users.views import CustomLoginView, UserEditProfileView, UserCreateProfileView, user_activation, reset_password

app_name = UsersConfig.name

urlpatterns = [
    path('', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', UserEditProfileView.as_view(), name='profile'),
    path('register/', UserCreateProfileView.as_view(), name='register'),
    path('activate/<str:token>/', user_activation, name='activate'),
    path('reset_password/', reset_password, name='reset_password'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    username = None
    email = models.EmailField(
        verbose_name='почта',
        unique=True
    )

    number = models.CharField(max_length=25, verbose_name='номер телефона')
    avatar = models.ImageField(verbose_name='аватар', upload_to='users/')
    country = models.CharField(max_length=35, verbose_name='страна')
    token = models.CharField(max_length=250, verbose_name='токен')
    token_created = models.DateTimeField(null=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

users/forms.py
from django.contrib.auth.forms import UserChangeForm
from django import forms

from users.models import User


class CustomEditUserForm(UserChangeForm):

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'avatar')

class NewCustomEditUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email', 'password')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

users/views.py
import datetime
import secrets

from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.hashers import make_password
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import UpdateView, CreateView

from config import settings
from users.forms import CustomEditUserForm, NewCustomEditUserForm
from users.models import User


class CustomLoginView(LoginView):
    template_name = 'users/login.html'


class UserCreateProfileView(CreateView):
    model = User
    form_class = NewCustomEditUserForm
    template_name = 'users/user_create.html'
    success_url = '/'

    def form_valid(self, form):
        if form.is_valid():
            self.object = form.save()
            ###
            self.object.token = make_password(self.object.password).replace('/','')
            self.object.token_created = datetime.datetime.now().astimezone()
            self.object.is_active = False
            ###
            self.object.set_password(form.data.get('password'))
            self.object.save()
            ###
            send_mail(
                subject='Активация',
                message=f'http://localhost:8000/users/activate/{self.object.token}/',
                from_email=settings.EMAIL_HOST_USER,
                recipient_list=[self.object.email],

            )
        return super().form_valid(form)


class UserEditProfileView(UpdateView):
    model = User
    template_name = 'users/profile.html'
    form_class = CustomEditUserForm
    success_url = reverse_lazy('prod:product')

    def get_object(self, queryset=None):
        return self.request.user

def user_activation(request, token):
    u = User.objects.filter(token=token).first()
    if u:
        u.is_active = True
        u.save()
    return redirect('http://localhost:8000')

def reset_password(request):
    if request.method == 'POST':

        password_reset_form = PasswordResetForm(request.POST)
        if password_reset_form.is_valid():
            mail = password_reset_form.cleaned_data['email']

            try:
                user = User.objects.get(email=mail)

            except Exception:
                user = False

            if user:
                new_password = secrets.token_urlsafe(18)[:15]
                user.set_password(new_password)
                user.save()
                send_mail(
                    subject='Смена пароля',
                    message=f'Пароль успешно обновлен, для входа в аккаун используйте следующие дынные:\nПочта: {mail}\nПароль: {new_password}',
                    from_email=settings.EMAIL_HOST_USER,
                    recipient_list=[mail],
                    fail_silently=False
                )
                return redirect('users:login')

    return render(request, 'users/password_recovery.html')

users/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Войти</button>
    <li><a class="text-muted" href="{% url 'users:reset_password' %}">Забыли пароль?</a></li>
</form>
</body>
</html>

users/templates/users/password_recovery.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Логин</title>
</head>
<body>
<div class="container">
    <h1>Забыли пароль?</h1>
    <p>Введите e-mail адрес и мы отправим новый пароль.</p>
    <form method="post" class="email-form">
        {% csrf_token %}
        <input type="email" name="email" autocomplete="email" class="form-control">
        <br>
        <button type="submit" class="p-2 btn btn-outline-dark">Отправить</button>

    </form>
</div>
</body>
</html>

users/templates/users/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить</button>
</form>
</body>
</html>

users/templates/users/user_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button  type="submit">Зарегистрироваться</button>
</form>
</body>
</html>

users/templates/users/user_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить</button>
</form>
</body>
</html>