config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('prod.urls', namespace='prod')),
    path('users/', include('users.urls', namespace='users')),
]

prod/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from prod.apps import ProdConfig
from prod.views import *

app_name = ProdConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='product'),
    path('product_create/', ProductCreateView.as_view(), name='product_create'),
    path('product_update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('product_delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
    path('product_detail/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='product_detail'),
    path('category_create/', CategoryCreateView.as_view(), name='category_create'),
    path('category_list/', CategoryListView.as_view(), name='category_list')
]

prod/models.py
from django.db import models

# Create your models here.

class Product(models.Model):
    STATUS_TRUE = 'True'
    STATUS_FALSE = 'False'
    STATUSES = (
        (STATUS_TRUE, 'Активна'),
        (STATUS_FALSE, 'Неактивна'),
    )
    name = models.CharField(max_length=250, verbose_name='Наименование продукта')
    price = models.IntegerField(verbose_name='Цена продукта')
    description = models.TextField(verbose_name='Описание')
    category = models.ForeignKey('Categories', on_delete=models.CASCADE)
    owner = models.ForeignKey('users.User', on_delete=models.CASCADE)
    status = models.CharField(choices=STATUSES, max_length=10, default=STATUS_FALSE, verbose_name='Признак публикации')

    class Meta:
        verbose_name = 'товар'
        verbose_name_plural = 'товары'

    def __str__(self):
        return f'{self.name} {self.category} {self.price} {self.description}'


class Version(models.Model):
    STATUS_ACTIVE = 'active'
    STATUS_INACTIVE = 'inactive'
    STATUSES = (
        (STATUS_ACTIVE, 'активна'),
        (STATUS_INACTIVE, 'неактивна'),
    )

    product = models.ForeignKey('Product', on_delete=models.CASCADE)
    version_number = models.IntegerField(verbose_name='Номер версии')
    version_name = models.CharField(max_length=250, verbose_name='Имя версии')
    version_status = models.CharField(choices=STATUSES, default=STATUS_INACTIVE, max_length=10, verbose_name='Статус')

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

    def __str__(self):
        return f'{self.version_number} {self.version_name} {self.version_status}'


class Categories(models.Model):

    category = models.CharField(max_length=150, verbose_name='Категория', unique=True)
    description = models.CharField(max_length=500, verbose_name='Описние')

    def __str__(self):
        return f'{self.category}'

prod/forms.py
from django import forms
from prod.models import Product, Version


class ProductForm(forms.ModelForm):
    black_list = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']

    class Meta:
        model = Product
        fields = '__all__'
        exclude = ['owner']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    def clean_name(self):

        name = self.cleaned_data['name']
        if name in self.black_list:
            raise forms.ValidationError('Содержит запрещенное слово в названии')
        return name

    def clean_description(self):
        description = self.cleaned_data['description']
        if description in self.black_list:
            raise forms.ValidationError('Содержит запрещенное слово в описании')
        return description


class VersionForm(forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

prod/views.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django.db import transaction
from django.forms import inlineformset_factory
from django.core.cache import cache

from config import settings
from prod.forms import ProductForm, VersionForm
from prod.models import Product, Version, Categories
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DeleteView, UpdateView, DetailView

from prod.services import get_categories_from_cache


class ProductListView(ListView):
    model = Product


class ProductDetailView(DetailView):
    model = Product

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['category'] = Product.objects.all()
        return context_data


class ProductCreateView(CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('prod:product')

    def form_valid(self, form):
        if form.is_valid():
            self.object = form.save(commit=False)
            self.object.owner = self.request.user
            self.object.save()
        return super(ProductCreateView, self).form_valid(form)


class ProductDeleteView(UserPassesTestMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('prod:product')

    def test_func(self):
        product = self.get_object()
        return self.request.user.has_perm('moderator') or product.owner == self.request.user


class ProductUpdateView(UserPassesTestMixin, UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('prod:product')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        FormSet = inlineformset_factory(self.model, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            formset = FormSet(self.request.POST, instance=self.object)
        else:
            formset = FormSet(instance=self.object)
        context_data['formset'] = formset
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        with transaction.atomic():
            if form.is_valid():
                self.object = form.save()  # Student
                if formset.is_valid():
                    formset.instance = self.object
                    formset.save()  # Subject

        return super().form_valid(form)

    def test_func(self):
        product = self.get_object()
        return self.request.user.has_perm('moderator') or product.owner == self.request.user


class CategoryCreateView(CreateView):
    model = Categories
    fields = '__all__'
    success_url = reverse_lazy('prod:category_list')


class CategoryListView(ListView):
    model = Categories

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['subjects'] = get_categories_from_cache()
        return context_data

prod/templates/prod/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
{% include 'prod/includes/inc_main_menu.html' %}
<head>
    <meta charset="UTF-8">
    <title>Продукты</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
{% if user.is_authenticated %}
<body>
{% block content %}
{% endblock %}
<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
{% else %}
<div class="col-8">Чтобы пользоваться сайтом, вам необходимо авторизоваться.</div>
{% endif %}
</html>

prod/templates/prod/categories_form.html
{% extends 'prod/base.html'%}
{% block content %}

<form method="post">
    <div class="container">
        <div class="col-5">
            <div class="card">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button class="p-2 btn btn-outline-primary bg-primary-subtle" type="submit">Отправить</button>
                </div>
            </div>
        </div>
    </div>
</form>

{% endblock %}

prod/templates/prod/categories_list.html
{% extends 'prod/base.html' %}
{% block content %}
<div class="container">
    <table class="table caption-top">
        <caption>Продукты</caption>
        <thead>
        <tr>
            <th scope="col">Категория</th>
            <th scope="col">Описание</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for object in subjects %}
        <tr>
            <td>{{object.category}}</td>
            <td>{{object.description}}</td>
            <td>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

prod/templates/prod/product_confirm_delete.html
{% extends 'prod/base.html'%}
{% block content %}
<div class="container">
    <div class="col-5">
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                <p><h5> Вы действительно хотите удалить продукт? </h5></p>
                <a class="p-2 btn btn-primary"
                   href="{% url 'prod:product' %}">Отменить</a>
                <button class="p-2 btn btn-danger" type="submit">Удалить</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

prod/templates/prod/product_detail.html
{% extends 'prod/base.html'%}
{% block content %}

<body>
<div class="card border-secondary mb-3" style="max-width: 18rem;">
    <div class="card-header">{{object.category}}</div>
    <div class="card-body text-secondary">
        <h5 class="card-title">{{object.name}}</h5>
        <p class="card-text">price {{object.price}}$</p>
        <p class="card-text">{{object.description}}</p>
    </div>
    <a class="p-2 btn btn-outline-secondary"
       href="{% url 'prod:product' %}">Назад</a>
<div class="card-header">Категории</div>
        {% for item in category %}
            <p>{{item.category}}</p>
        {% endfor %}
</div>
</body>

{% endblock %}

prod/templates/prod/product_form.html
{% extends 'prod/base.html'%}
{% block content %}

<form method="post">
    <div class="container">
        <div class="col-5">
            <div class="card">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button class="p-2 btn btn-outline-primary bg-primary-subtle" type="submit">Отправить</button>
                </div>
            </div>
        </div>
        <div class="col-3">
            <div class="card">
                <div class="card-body">
                    <div class="formset">
                        {{ formset.management_form }}
                        {% for form in formset.forms %}
                        <div class="formset_row">
                            {% for field in form.visible_fields %}
                            <div class="formset-col">
                                {% if forloop.first %}
                                {% for hidden in form.hidden_fields %}
                                {{ hidden }}
                                {% endfor %}
                                {% endif %}
                                {{ field.errors.as_ul }}
                                {% if not forloop.last %}
                                {{field.label}}
                                {% endif %}
                                {{ field }}
                            </div>
                            {% endfor %}
                            </button>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>

</form>
<script src="https://code.jquery.com/jquery-3.6.3.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.formset/1.2.2/jquery.formset.min.js"
        integrity="sha512-ltwjKsDTo3hW/wV66ZaEkf2wOAFxmg7rWM76J8kOcYKLSKy44WBYO/BFaNNH3NGDS8BSz3meB9wtSnm41oL+pA=="
        crossorigin="anonymous" referrerpolicy="no-referrer">
</script>
<script>
    $('.formset_row').formset({
    addText: '<span class="btn btn-outline-primary">Добавить предмет</span>',
    deleteText: '<span class="btn btn-outline-danger">Удалить</span>',
    prefix: 'tag_set',
    });


</script>
{% endblock %}

prod/templates/prod/product_list.html
{% extends 'prod/base.html' %}
{% block content %}
<div class="container">
    <table class="table caption-top">
        <caption>Продукты</caption>
        <thead>
        <tr>
            <th scope="col">Наименование</th>
            <th scope="col">Цена</th>
            <th scope="col">Категория</th>
            <th scope="col">Создатель</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for object in object_list %}
        <tr>
            <td>{{object.name}}</td>
            <td>{{object.price}}</td>
            <td>{{object.category}}</td>
            <td>{{object.owner}}</td>
            <td>
                <a class="p-1 btn btn-primary" href="{% url 'prod:product_update' object.pk %}">Редактировать</a>
                <a class="p-1 btn btn-danger" href="{% url 'prod:product_delete' object.pk %}">Удалить</a>
                <a class="p-1 btn btn-info" href="{% url 'prod:product_detail' object.pk %}">Детали</a>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}